#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "$HOME/.zprezto/init.zsh" ]]; then
  source "$HOME/.zprezto/init.zsh"
fi

# Custom functions
fpath=(
  ~/.zfunc
  $fpath
)
autoload ~/.zfunc/*

# Alternate profiles
emulate sh -c '. ~/.profile'
emulate bash -c '. ~/.bash_profile'
